version: "3.9"

services:
  door_detector:
    container_name: door_detector
    build:
      context: .
      dockerfile: Dockerfile
    image: door_detector
    runtime: nvidia
    privileged: true
    network_mode: host
    environment:
      - DISPLAY=${DISPLAY}
      - XAUTHORITY=${XAUTHORITY}
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ${HOME}/.Xauthority:${HOME}/.Xauthority:rw
      - /home/ias/Indoor_Navigation:/app
      - /home/ias/Indoor_Navigation/vscode-root:/app/.vscode-root
    devices:
      - /dev/bus/usb:/dev/bus/usb  #access USB
    stdin_open: true
    tty: true



